### ISSUE TITLE
Tags are not being updated

### ISSUE THREAD

**Issue by Hornbydd** [wri/arcpy_metadata#6]
I have downloaded and installed the package. I am able to connect to the metadata of a file geodatabase featureclass. When I update the title and then use finish to commit it, it fails (without any error message).

Also if I write some tags, for example:

`met.tags = ["AAAA","BBBB"]`

then the next line is:

`met.place_keywords = ["qqqqqqq","EEEEEEEEE"]`

and then commit with `met.finish()` the tags are overwritten by the place keywords!

**Comment by thomas-maschler** [comment]
This seems to be fixed
